function [CapacitanceMatrixChoice] = Menu_CapacitanceMatrix_DefaultParameters_Generator
field1 = 'Regular_Round_Matrix';
value1 = 1;
field2 = 'Eliptical1_Long_In_X_Direction';
value2 = 0;
field3 = 'Eliptical1_Long_In_Y_Direction';
value3 = 0;
field4 = 'OscliatingRowsOnly';
value4 = 0;
field5 = 'OscilatingLinesAndRows';
value5 = 0;
field6 = 'SideWays_Matrix';
value6 = 0;
field7 = 'Increasing_Screeninglength_X_Matrix';
value7 = 0;
field8 = 'Decreasing_Screeninglength_1X_Matrix';
value8 = 0;
field9 = 'Increasing_Screeninglength_X2_Matrix';
value9 = 0;
field10 = 'Y_Gradient_10timeIncrease_Matrix';
value10 = 0;
GoBack = 0;

CapacitanceMatrixChoice = struct(field1,value1,field2,value2,field3,value3,field4,value4,field5,value5,field6,value6,field7,value7,field8,value8,field9,value9,field10,value10);
